In [1]:
# Necessary Libraries
import pandas as pd
import re

#### Load the Dataset

Need to skip the first 4 rows to have a proper tabular format.

In [2]:
# Load the datasets
df_gdp = pd.read_csv('gdp_per_capita.csv', skiprows = 4)

In [18]:
test = pd.read_csv('gdp_per_capita.csv', skiprows = 4)

In [19]:
test.shape

(266, 69)

#### Check the Structure

In [3]:
# Remove leading & trailing whitespace + replace multiple spaces within names to a single underscore
df_gdp.columns = df_gdp.columns.str.strip().str.replace(r'\s+', '_', regex=True)

# Duplicate
# Automatically detect categorical/object columns
cat_cols = df_gdp.select_dtypes(include=['object', 'category']).columns
# Strip leading and trailing spaces from all categorical columns
df_gdp[cat_cols] = df_gdp[cat_cols].apply(lambda x: x.str.strip())

# Check dataset structures
print("Dataset Structures: ")
display(df_gdp.info())

# First 5 rows
print("\nFirst 5 rows: ")
display(df_gdp.head())

# Last 5 rows
print("\nLast 5 rows: ")
display(df_gdp.tail())

# Check the descriptive statistics of the datasete
print('\nCategorical Variables:')
display(df_gdp.describe(include = 'object'))

print('\nNumerical Variables: ')
display(df_gdp.describe(include = 'number'))

# Check missing values 
print("\nMissing values count for each column: ")
display(df_gdp.isnull().sum())  

print("\nMissing values percentage: ")
display(df_gdp.isna().mean() * 100)   

num_duplicates = df_gdp.duplicated().sum()
print(f"\nTotal duplicate rows: {num_duplicates}")

Dataset Structures:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country_Name    266 non-null    object
 1   Country_Code    266 non-null    object
 2   Indicator_Name  266 non-null    object
 3   Indicator_Code  266 non-null    object
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            157 non-null    float64
 7   1963            157 non-null    float64
 8   1964            157 non-null    float64
 9   1965            163 non-null    float64
 10  1966            164 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            259 non-null    float64
 60  2016            258 non-null    float64
 61  2017            258 non-null    float64
 62  2018            258 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            255 non-null    float64
 67  2023            243 non-null    float64
 68  Unnamed:_68     0 non-null      float64
dtypes: float64(65), object(4)
memory usage: 143.5+ KB

None

First 5 rows:

,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed:_68
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27458.225331,27441.529662,28440.051964,30082.127645,31096.205074,22855.932320,27200.061079,30559.533535,33984.790620,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.132432,186.947182,197.408105,225.447007,209.005786,226.883067,...,1479.564123,1329.777824,1520.171298,1538.924188,1493.780445,1344.080962,1522.590088,1628.024526,1659.515290,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,415.707417,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.938353,127.452629,133.825452,139.006714,148.547736,155.563837,...,1845.767804,1616.843198,1560.162999,1703.896392,1783.654365,1664.249176,1747.840549,1777.235012,1568.724310,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3213.902611,1807.952941,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2308.159767,NaN

Last 5 rows:

,Country_Name,Country_Code,Indicator_Name,Indicator_Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed:_68
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3520.628507,3759.449591,4009.317993,4384.186241,4415.997161,4310.888247,5270.426702,5290.947472,5960.158205,NaN
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1362.173794,975.359407,811.165964,633.887206,623.376165,559.564673,522.173513,615.702079,477.409029,NaN
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,6112.273825,5651.205852,6618.335083,6914.178032,6533.711210,5580.603831,6843.399419,6523.410978,6022.542542,NaN
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1295.877887,1239.085279,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,NaN
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.419762,279.016467,275.545586,277.005679,281.744516,294.145335,...,1386.422847,1407.415364,3448.082537,2271.853335,1684.027904,1730.413489,1724.387731,2040.552459,2156.034004,NaN

Categorical Variables:

       Country_Name Country_Code                Indicator_Name  Indicator_Code
count           266          266                           266             266
unique          266          266                             1               1
top        Zimbabwe          ZWE  GDP per capita (current US$)  NY.GDP.PCAP.CD
freq              1            1                           266             266

Numerical Variables:

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed:_68
count,151.000000,154.000000,157.000000,157.000000,157.000000,163.000000,164.000000,167.000000,168.000000,168.000000,...,259.000000,258.000000,258.000000,258.000000,259.000000,258.000000,258.000000,255.000000,243.000000,0.0
mean,467.442620,485.093509,537.697945,567.863079,613.684342,668.713645,712.474795,729.500111,763.589758,827.476481,...,15670.464509,15797.163346,16607.583807,17589.293961,17486.413245,16243.388438,18709.687371,18969.630109,19039.354135,NaN
std,592.170001,615.616009,727.725483,750.445707,808.011105,837.331808,903.750656,936.300119,982.894676,1059.404443,...,23568.143103,23691.904327,24446.348036,25945.047195,25637.962412,24324.270020,28638.433830,28610.222253,28434.626823,NaN
min,25.084776,27.265454,27.947004,25.803984,17.332201,15.117863,11.801322,16.545381,21.545341,21.510318,...,280.966831,235.286205,236.694473,224.899392,210.236495,210.008140,214.091455,250.634225,193.007146,NaN
25%,120.496147,125.308032,130.042570,139.006714,141.534669,155.565411,162.750106,161.727133,166.230264,175.154789,...,1999.690173,1952.493233,2153.335677,2147.302872,2188.022478,2067.933047,2383.316409,2347.929586,2361.879156,NaN
50%,220.074550,205.021254,210.805414,231.919408,243.897431,270.830585,280.506935,283.733706,301.234016,316.891727,...,6154.495935,5968.538696,6446.312069,6865.573107,6804.149231,6247.596924,7054.635805,7606.237525,7820.232404,NaN
75%,484.034848,505.371294,563.423009,604.536855,694.952087,833.209067,885.874482,844.844588,847.350025,901.091256,...,19060.625424,19035.379272,20845.374575,22657.440241,22462.976051,19516.369130,22099.372211,22914.832751,22717.803092,NaN
max,2999.864872,3059.160821,4748.392844,4444.523086,4378.784298,4023.990378,4176.110382,4325.959351,4684.588403,5019.998186,...,170437.101188,173604.753556,170663.375248,188298.315668,193746.785647,176891.886538,223823.363960,226052.001905,256580.515123,NaN

Missing values count for each column:

Country_Name        0
Country_Code        0
Indicator_Name      0
Indicator_Code      0
1960              115
                 ...
2020                8
2021                8
2022               11
2023               23
Unnamed:_68       266
Length: 69, dtype: int64

Missing values percentage:

Country_Name        0.000000
Country_Code        0.000000
Indicator_Name      0.000000
Indicator_Code      0.000000
1960               43.233083
                     ...
2020                3.007519
2021                3.007519
2022                4.135338
2023                8.646617
Unnamed:_68       100.000000
Length: 69, dtype: float64

Total duplicate rows: 0

#### Select Necessary Columns

In [4]:
# Select only these columns (subset)
selected_cols = ['Country_Name', 'Country_Code', '2018', '2019', '2020', '2021', '2022']

df_gdp = df_gdp[selected_cols]

#### Renaming Columns

In [5]:
df_gdp.rename(columns={
    'Country_Name': 'country',
    'Country_Code': 'country_code'
}, inplace=True)

#### Convert Wide to Long

In [6]:
years = ['2018', '2019', '2020', '2021', '2022']

df_gdp = df_gdp.melt(
    id_vars=['country', 'country_code'],   # Include Country Code
    value_vars= years,                          # Columns to unpivot
    var_name='year_gdp_capita',                           # New column for years
    value_name='gdp_per_capita'                # New column for values
)

df_gdp = df_gdp.dropna(subset=['gdp_per_capita'])
df_gdp['year_gdp_capita'] = df_gdp['year_gdp_capita'].astype(int)

df_gdp = df_gdp.reset_index(drop=True)

#### Handle Multiple Years

In [7]:
# Filter only rows with year ≤ 2022
df_gdp = df_gdp[df_gdp['year_gdp_capita'] <= 2022]

# For each country, get its latest year
latest_year_per_country = df_gdp.groupby('country')['year_gdp_capita'].max().reset_index()

# Merge back to get full rows matching latest year for each country
df_gdp = df_gdp.merge(latest_year_per_country, on=['country', 'year_gdp_capita'], how='inner')

# Drop year
df_gdp.drop(columns=["year_gdp_capita"], inplace=True)

#### Handling Country Variation

In [8]:
df_gdp['country'].unique()

array(['Cuba', 'Greenland', 'Isle of Man', 'St. Martin (French part)',
       'Aruba', 'Africa Eastern and Southern', 'Afghanistan',
       'Africa Western and Central', 'Angola', 'Albania', 'Andorra',
       'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso',
       'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas, The',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan',
       'Botswana', 'Central African Republic', 'Canada',
       'Central Europe and the Baltics', 'Switzerland', 'Channel Islands',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica',
       'Caribbean small states', 'Curacao', 'Cayman Islands', 'Cyprus',
       'Czechia', 'Germany', 'Djibouti', 'Dominica', 'Denmark',
       'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Spain', 'Estonia', 'Ethiopia', 'European Union',
       'Fragile and conflict affected situations', 'Finland', 'Fiji',
       'France', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon',
       'United Kingdom', 'Georgia', 'Ghana', 'Guinea', 'Gambia, The',
       'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Grenada',
       'Guatemala', 'Guam', 'Guyana', 'High income',
       'Hong Kong SAR, China', 'Honduras',
       'Heavily indebted poor countries (HIPC)', 'Croatia', 'Haiti',
       'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total',
       'IDA blend', 'Indonesia', 'IDA only', 'India', 'Ireland',
       'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel', 'Italy',
       'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis',
       'Korea, Rep.', 'Kuwait',
       'Latin America & Caribbean (excluding high income)', 'Lao PDR',
       'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Low income',
       'Liechtenstein', 'Sri Lanka', 'Lower middle income',
       'Low & middle income', 'Lesotho', 'Late-demographic dividend',
       'Lithuania', 'Luxembourg', 'Latvia', 'Macao SAR, China', 'Morocco',
       'Monaco', 'Moldova', 'Madagascar', 'Maldives',
       'Middle East & North Africa', 'Mexico', 'Marshall Islands',
       'Middle income', 'North Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Middle East & North Africa (excluding high income)', 'Montenegro',
       'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania',
       'Mauritius', 'Malawi', 'Malaysia', 'North America', 'Namibia',
       'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands',
       'Norway', 'Nepal', 'Nauru', 'New Zealand', 'OECD members', 'Oman',
       'Other small states', 'Pakistan', 'Panama', 'Peru', 'Philippines',
       'Palau', 'Papua New Guinea', 'Poland', 'Pre-demographic dividend',
       'Puerto Rico', 'Portugal', 'Paraguay', 'West Bank and Gaza',
       'Pacific island small states', 'Post-demographic dividend',
       'French Polynesia', 'Qatar', 'Romania', 'Russian Federation',
       'Rwanda', 'South Asia', 'Saudi Arabia', 'Sudan', 'Senegal',
       'Singapore', 'Solomon Islands', 'Sierra Leone', 'El Salvador',
       'San Marino', 'Somalia', 'Serbia',
       'Sub-Saharan Africa (excluding high income)', 'Sub-Saharan Africa',
       'Small states', 'Sao Tome and Principe', 'Suriname',
       'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Sint Maarten (Dutch part)', 'Seychelles', 'Syrian Arab Republic',
       'Turks and Caicos Islands', 'Chad',
       'East Asia & Pacific (IDA & IBRD countries)',
       'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)',
       'Tonga', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Tunisia', 'Turkiye', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine',
       'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Virgin Islands (U.S.)',
       'Viet Nam', 'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [9]:
df_gdp.head()

                    country country_code  gdp_per_capita
0                      Cuba          CUB     9605.261251
1                 Greenland          GRL    57116.295771
2               Isle of Man          IMN    94299.969349
3  St. Martin (French part)          MAF    21668.377653
4                     Aruba          ABW    30559.533535

In [10]:
# Load the datasets
df_gini = pd.read_csv('gini_procecssed.csv')

In [11]:
df_merged = pd.merge(
    df_gini,
    df_gdp,
    on='country_code',  # Common column for joining
    how='inner'         # Inner Join: keep only matching rows
)

In [12]:
df_merged.head(10)

    country_x country_code      gini   country_y  gdp_per_capita
0     Albania          ALB  0.294196     Albania     6846.426143
1     Algeria          DZA  0.276157     Algeria     4961.552577
2      Angola          AGO  0.512640      Angola     2929.694455
3   Argentina          ARG  0.407365   Argentina    13935.681111
4     Armenia          ARM  0.279453     Armenia     6571.974455
5   Australia          AUS  0.343326   Australia    64997.013654
6     Austria          AUT  0.307016     Austria    52176.664914
7  Azerbaijan          AZE  0.265549  Azerbaijan     7770.594223
8  Bangladesh          BGD  0.333732  Bangladesh     2716.485927
9     Belarus          BLR  0.243834     Belarus     7994.648061

In [13]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_x       166 non-null    object
 1   country_code    166 non-null    object
 2   gini            166 non-null    float64
 3   country_y       166 non-null    object
 4   gdp_per_capita  166 non-null    float64
dtypes: float64(2), object(3)
memory usage: 6.6+ KB

#### Drop Redundant Columns and Rename Columns after Merge

In [14]:
df_merged.drop(columns=["country_y"], inplace=True)
df_merged.rename(columns={
    'country_x': 'country'
}, inplace=True)

In [15]:
df_merged.head(15)

       country country_code      gini  gdp_per_capita
0      Albania          ALB  0.294196     6846.426143
1      Algeria          DZA  0.276157     4961.552577
2       Angola          AGO  0.512640     2929.694455
3    Argentina          ARG  0.407365    13935.681111
4      Armenia          ARM  0.279453     6571.974455
5    Australia          AUS  0.343326    64997.013654
6      Austria          AUT  0.307016    52176.664914
7   Azerbaijan          AZE  0.265549     7770.594223
8   Bangladesh          BGD  0.333732     2716.485927
9      Belarus          BLR  0.243834     7994.648061
10     Belgium          BEL  0.265776    50807.204708
11      Belize          BLZ  0.532310     7068.454783
12       Benin          BEN  0.343958     1264.707660
13      Bhutan          BTN  0.284599     3711.327679
14     Bolivia          BOL  0.409133     3643.928270

In [16]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         166 non-null    object
 1   country_code    166 non-null    object
 2   gini            166 non-null    float64
 3   gdp_per_capita  166 non-null    float64
dtypes: float64(2), object(2)
memory usage: 5.3+ KB

In [17]:
df_merged.to_csv('gini_gdp.csv', index=False)