In [18]:
# Necessary Libraries
import pandas as pd
import re

#### Load the Dataset

In [19]:
df_happiness = pd.read_excel('world_happiness_report_2022.xls')

In [20]:
df_happiness.shape

(147, 12)

In [3]:
# Remove leading & trailing whitespace + replace multiple spaces within names to a single underscore
df_happiness.columns = df_happiness.columns.str.strip().str.replace(r'\s+', '_', regex=True)

# Duplicate
# Automatically detect categorical/object columns
cat_cols = df_happiness.select_dtypes(include=['object', 'category']).columns
# Strip leading and trailing spaces from all categorical columns
df_happiness[cat_cols] = df_happiness[cat_cols].apply(lambda x: x.str.strip())

# Check dataset structures
print("Dataset Structures: ")
display(df_happiness.info())

# First 5 rows
print("\nFirst 5 rows: ")
display(df_happiness.head())

# Last 5 rows
print("\nLast 5 rows: ")
display(df_happiness.tail())

# Check the descriptive statistics of the datasete
print('\nCategorical Variables:')
display(df_happiness.describe(include = 'object'))

print('\nNumerical Variables: ')
display(df_happiness.describe(include = 'number'))

# Check missing values 
print("\nMissing values count for each column: ")
display(df_happiness.isnull().sum())  

print("\nMissing values percentage: ")
display(df_happiness.isna().mean() * 100)   

num_duplicates = df_happiness.duplicated().sum()
print(f"\nTotal duplicate rows: {num_duplicates}")

Dataset Structures:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   RANK                                        147 non-null    int64
 1   Country                                     147 non-null    object
 2   Happiness_score                             146 non-null    float64
 3   Whisker-high                                146 non-null    float64
 4   Whisker-low                                 146 non-null    float64
 5   Dystopia_(1.83)_+_residual                  146 non-null    float64
 6   Explained_by:_GDP_per_capita                146 non-null    float64
 7   Explained_by:_Social_support                146 non-null    float64
 8   Explained_by:_Healthy_life_expectancy       146 non-null    float64
 9   Explained_by:_Freedom_to_make_life_choices  146 non-null    float64
 10  Explained_by:_Generosity                    146 non-null    float64
 11  Explained_by:_Perceptions_of_corruption     146 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 13.9+ KB

None

First 5 rows:

,RANK,Country,Happiness_score,Whisker-high,Whisker-low,Dystopia_(1.83)_+_residual,Explained_by:_GDP_per_capita,Explained_by:_Social_support,Explained_by:_Healthy_life_expectancy,Explained_by:_Freedom_to_make_life_choices,Explained_by:_Generosity,Explained_by:_Perceptions_of_corruption
0,1,Finland,7.8210,7.886425,7.755575,2.518052,1.891628,1.258108,0.775206,0.735590,0.108733,0.533658
1,2,Denmark,7.6362,7.709897,7.562503,2.225632,1.952595,1.242681,0.776644,0.718918,0.187626,0.532079
2,3,Iceland,7.5575,7.651076,7.463924,2.320185,1.935726,1.319914,0.802622,0.718194,0.269616,0.191204
3,4,Switzerland,7.5116,7.586394,7.436806,2.152746,2.025970,1.226074,0.822048,0.676947,0.146822,0.461004
4,5,Netherlands,7.4149,7.471265,7.358534,2.136937,1.944578,1.205848,0.786738,0.650682,0.271076,0.419083

Last 5 rows:

,RANK,Country,Happiness_score,Whisker-high,Whisker-low,Dystopia_(1.83)_+_residual,Explained_by:_GDP_per_capita,Explained_by:_Social_support,Explained_by:_Healthy_life_expectancy,Explained_by:_Freedom_to_make_life_choices,Explained_by:_Generosity,Explained_by:_Perceptions_of_corruption
142,143,Rwanda*,3.2682,3.462218,3.074182,0.536299,0.785252,0.132698,0.461527,0.621479,0.186662,0.544236
143,144,Zimbabwe,2.9951,3.109822,2.880378,0.547529,0.946604,0.690460,0.270086,0.329203,0.106265,0.104943
144,145,Lebanon,2.9553,3.048951,2.861649,0.215537,1.392068,0.497999,0.630964,0.102799,0.082191,0.033761
145,146,Afghanistan,2.4038,2.468731,2.338869,1.263403,0.757994,0.000000,0.288626,0.000000,0.088873,0.004882
146,147,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Categorical Variables:

        Country
count       147
unique      147
top     Finland
freq          1

Numerical Variables:

,RANK,Happiness_score,Whisker-high,Whisker-low,Dystopia_(1.83)_+_residual,Explained_by:_GDP_per_capita,Explained_by:_Social_support,Explained_by:_Healthy_life_expectancy,Explained_by:_Freedom_to_make_life_choices,Explained_by:_Generosity,Explained_by:_Perceptions_of_corruption
count,147.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000
mean,74.000000,5.553575,5.673613,5.433538,1.831807,1.410429,0.905834,0.586146,0.517225,0.147372,0.154758
std,42.579338,1.086814,1.065649,1.109374,0.534971,0.421655,0.280123,0.176352,0.145833,0.082763,0.127522
min,1.000000,2.403800,2.468731,2.338869,0.187416,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.500000,4.888550,5.006018,4.754731,1.555475,1.095578,0.732114,0.462953,0.440506,0.088723,0.068087
50%,74.000000,5.568700,5.680081,5.453245,1.894558,1.445134,0.957799,0.621445,0.543633,0.132417,0.119459
75%,110.500000,6.305025,6.448932,6.189783,2.152897,1.785087,1.114658,0.720065,0.625763,0.197554,0.198213
max,147.000000,7.821000,7.886425,7.755575,2.844388,2.209395,1.319914,0.941829,0.740039,0.467926,0.586828

Missing values count for each column:

RANK                                          0
Country                                       0
Happiness_score                               1
Whisker-high                                  1
Whisker-low                                   1
Dystopia_(1.83)_+_residual                    1
Explained_by:_GDP_per_capita                  1
Explained_by:_Social_support                  1
Explained_by:_Healthy_life_expectancy         1
Explained_by:_Freedom_to_make_life_choices    1
Explained_by:_Generosity                      1
Explained_by:_Perceptions_of_corruption       1
dtype: int64

Missing values percentage:

RANK                                          0.000000
Country                                       0.000000
Happiness_score                               0.680272
Whisker-high                                  0.680272
Whisker-low                                   0.680272
Dystopia_(1.83)_+_residual                    0.680272
Explained_by:_GDP_per_capita                  0.680272
Explained_by:_Social_support                  0.680272
Explained_by:_Healthy_life_expectancy         0.680272
Explained_by:_Freedom_to_make_life_choices    0.680272
Explained_by:_Generosity                      0.680272
Explained_by:_Perceptions_of_corruption       0.680272
dtype: float64

Total duplicate rows: 0

#### Drop Last Row (NULL)

In [4]:
df_happiness = df_happiness.drop(index=146)  # Drop row with index 3

#### Select a Subset of Column

In [5]:
# Select only these columns (subset)
selected_cols = ['Country', 'Happiness_score']

df_happiness = df_happiness[selected_cols]

#### Rename Column

In [6]:
df_happiness.rename(columns={
    'Country': 'country',
    'Happiness_score': 'happiness_score'
}, inplace=True)

In [7]:
df_happiness.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          146 non-null    object
 1   happiness_score  146 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.4+ KB

#### Clean Country Names

In [8]:
df_happiness['country'] = df_happiness['country'].str.replace('*', '', regex=False).str.strip()

#### Merge with the other datasets

In [9]:
df_gdp_gini = pd.read_csv('gini_gdp.csv')

In [10]:
df_gdp_gini['country'].unique()

array(['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bangladesh', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia', 'Samoa',
       'Sao Tome and Principe', 'Senegal', 'Serbia', 'Seychelles',
       'Sierra Leone', 'Slovakia', 'Slovenia', 'Solomon Islands',
       'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan',
       'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vietnam', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [11]:
df_happiness['country'].unique()

array(['Finland', 'Denmark', 'Iceland', 'Switzerland', 'Netherlands',
       'Luxembourg', 'Sweden', 'Norway', 'Israel', 'New Zealand',
       'Austria', 'Australia', 'Ireland', 'Germany', 'Canada',
       'United States', 'United Kingdom', 'Czechia', 'Belgium', 'France',
       'Bahrain', 'Slovenia', 'Costa Rica', 'United Arab Emirates',
       'Saudi Arabia', 'Taiwan Province of China', 'Singapore', 'Romania',
       'Spain', 'Uruguay', 'Italy', 'Kosovo', 'Malta', 'Lithuania',
       'Slovakia', 'Estonia', 'Panama', 'Brazil', 'Guatemala',
       'Kazakhstan', 'Cyprus', 'Latvia', 'Serbia', 'Chile', 'Nicaragua',
       'Mexico', 'Croatia', 'Poland', 'El Salvador', 'Kuwait', 'Hungary',
       'Mauritius', 'Uzbekistan', 'Japan', 'Honduras', 'Portugal',
       'Argentina', 'Greece', 'South Korea', 'Philippines', 'Thailand',
       'Moldova', 'Jamaica', 'Kyrgyzstan', 'Belarus', 'Colombia',
       'Bosnia and Herzegovina', 'Mongolia', 'Dominican Republic',
       'Malaysia', 'Bolivia', 'China', 'Paraguay', 'Peru', 'Montenegro',
       'Ecuador', 'Vietnam', 'Turkmenistan', 'North Cyprus', 'Russia',
       'Hong Kong S.A.R. of China', 'Armenia', 'Tajikistan', 'Nepal',
       'Bulgaria', 'Libya', 'Indonesia', 'Ivory Coast', 'North Macedonia',
       'Albania', 'South Africa', 'Azerbaijan', 'Gambia', 'Bangladesh',
       'Laos', 'Algeria', 'Liberia', 'Ukraine', 'Congo', 'Morocco',
       'Mozambique', 'Cameroon', 'Senegal', 'Niger', 'Georgia', 'Gabon',
       'Iraq', 'Venezuela', 'Guinea', 'Iran', 'Ghana', 'Turkey',
       'Burkina Faso', 'Cambodia', 'Benin', 'Comoros', 'Uganda',
       'Nigeria', 'Kenya', 'Tunisia', 'Pakistan',
       'Palestinian Territories', 'Mali', 'Namibia',
       'Eswatini, Kingdom of', 'Myanmar', 'Sri Lanka', 'Madagascar',
       'Egypt', 'Chad', 'Ethiopia', 'Yemen', 'Mauritania', 'Jordan',
       'Togo', 'India', 'Zambia', 'Malawi', 'Tanzania', 'Sierra Leone',
       'Lesotho', 'Botswana', 'Rwanda', 'Zimbabwe', 'Lebanon',
       'Afghanistan'], dtype=object)

In [12]:
# Get unique values from both datasets
set1 = set(df_happiness['country'].unique())
set2 = set(df_gdp_gini['country'].unique())

# Values in df1 but not in df2
diff_1_not_in_2 = set1 - set2

# Values in df2 but not in df1
diff_2_not_in_1 = set2 - set1

print("Country in df_happiness but not in df_gdp_gini: \n", diff_1_not_in_2)
print("\nCountry in df_gdp_gini but not in df_happiness: \n", diff_2_not_in_1)

Country in df_happiness but not in df_gdp_gini:
 {'Hong Kong S.A.R. of China', 'Singapore', 'Eswatini, Kingdom of', 'Kosovo', 'Saudi Arabia', 'Taiwan Province of China', 'New Zealand', 'Ivory Coast', 'Kuwait', 'Bahrain', 'Palestinian Territories', 'Afghanistan', 'Libya', 'Cambodia', 'North Cyprus', 'Venezuela'}

Country in df_gdp_gini but not in df_happiness:
 {'Syria', 'Maldives', 'East Timor', 'Seychelles', 'Saint Lucia', 'Samoa', 'Central African Republic', 'Haiti', 'Trinidad and Tobago', 'Bhutan', 'Belize', 'Nauru', 'Sao Tome and Principe', 'Sudan', 'Fiji', 'Qatar', 'Guinea-Bissau', 'Tuvalu', 'Marshall Islands', 'Papua New Guinea', 'Guyana', 'Micronesia', 'Cape Verde', 'Eswatini', 'Vanuatu', 'Burundi', 'Democratic Republic of Congo', 'Angola', 'Solomon Islands', 'Suriname', 'Tonga', 'Djibouti', "Cote d'Ivoire", 'Grenada', 'Kiribati', 'Palestine'}

In [13]:
country_mapping = {
    'Palestinian Territories': 'Palestine',
    "Cote d'Ivoire": 'Ivory Coast',
    'North Cyprus': 'Cyprus',
    'Hong Kong S.A.R. of China': 'Hong Kong',
    'Taiwan Province of China': 'Taiwan',
    'Eswatini, Kingdom of': 'Eswatini',
    'Kosovo': 'Kosovo',  # only if named differently elsewhere
}

df_happiness['country'] = df_happiness['country'].replace(country_mapping)
df_gdp_gini['country'] = df_gdp_gini['country'].replace(country_mapping)

In [14]:
df_merged = pd.merge(
    df_gdp_gini,
    df_happiness,
    on='country',  # Common column for joining
    how='inner'         # Inner Join: keep only matching rows
)

In [15]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          134 non-null    object
 1   country_code     134 non-null    object
 2   gini             134 non-null    float64
 3   gdp_per_capita   134 non-null    float64
 4   happiness_score  134 non-null    float64
dtypes: float64(3), object(2)
memory usage: 5.4+ KB

In [16]:
df_merged.head()

     country country_code      gini  gdp_per_capita  happiness_score
0    Albania          ALB  0.294196     6846.426143           5.1988
1    Algeria          DZA  0.276157     4961.552577           5.1223
2  Argentina          ARG  0.407365    13935.681111           5.9670
3    Armenia          ARM  0.279453     6571.974455           5.3986
4  Australia          AUS  0.343326    64997.013654           7.1621

In [17]:
df_merged.to_csv('happiness_gini_gdp.csv', index=False)