In [1]:
# Necessary Libraries
import pandas as pd
import re

pd.set_option('display.max_columns', None)

#### Load the Dataset

In [2]:
df_oecd = pd.read_csv('oecd_net_social_spending.csv')

In [21]:
test = pd.read_csv('oecd_net_social_spending.csv')

In [22]:
test.shape

(217, 34)

In [3]:
# Remove leading & trailing whitespace + replace multiple spaces within names to a single underscore
df_oecd.columns = df_oecd.columns.str.strip().str.replace(r'\s+', '_', regex=True)

# Duplicate
# Automatically detect categorical/object columns
cat_cols = df_oecd.select_dtypes(include=['object', 'category']).columns
# Strip leading and trailing spaces from all categorical columns
df_oecd[cat_cols] = df_oecd[cat_cols].apply(lambda x: x.str.strip())

# Check dataset structures
print("Dataset Structures: ")
display(df_oecd.info())

# First 5 rows
print("\nFirst 5 rows: ")
display(df_oecd.head())

# Last 5 rows
print("\nLast 5 rows: ")
display(df_oecd.tail())

# Check the descriptive statistics of the datasete
print('\nCategorical Variables:')
display(df_oecd.describe(include = 'object'))

print('\nNumerical Variables: ')
display(df_oecd.describe(include = 'number'))

# Check missing values 
print("\nMissing values count for each column: ")
display(df_oecd.isnull().sum())  

print("\nMissing values percentage: ")
display(df_oecd.isna().mean() * 100)   

num_duplicates = df_oecd.duplicated().sum()
print(f"\nTotal duplicate rows: {num_duplicates}")

Dataset Structures:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 217 non-null    object
 1   STRUCTURE_ID              217 non-null    object
 2   STRUCTURE_NAME            217 non-null    object
 3   ACTION                    217 non-null    object
 4   REF_AREA                  217 non-null    object
 5   Reference_area            217 non-null    object
 6   FREQ                      217 non-null    object
 7   Frequency_of_observation  217 non-null    object
 8   MEASURE                   217 non-null    object
 9   Measure                   217 non-null    object
 10  UNIT_MEASURE              217 non-null    object
 11  Unit_of_measure           217 non-null    object
 12  EXPEND_SOURCE             217 non-null    object
 13  Expenditure_source        217 non-null    object
 14  SPENDING_TYPE             217 non-null    object
 15  Spending_type             217 non-null    object
 16  PROGRAMME_TYPE            217 non-null    object
 17  Programme_type            217 non-null    object
 18  PRICE_BASE                217 non-null    object
 19  Price_base                217 non-null    object
 20  TIME_PERIOD               217 non-null    int64
 21  Time_period               0 non-null      float64
 22  OBS_VALUE                 217 non-null    float64
 23  Observation_value         0 non-null      float64
 24  OBS_STATUS                217 non-null    object
 25  Observation_status        217 non-null    object
 26  UNIT_MULT                 217 non-null    int64
 27  Unit_multiplier           217 non-null    object
 28  DECIMALS                  217 non-null    int64
 29  Decimals                  217 non-null    object
 30  CURRENCY                  217 non-null    object
 31  Currency                  217 non-null    object
 32  BASE_PER                  0 non-null      float64
 33  Base_period               0 non-null      float64
dtypes: float64(5), int64(3), object(26)
memory usage: 57.8+ KB

None

First 5 rows:

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference_area,FREQ,Frequency_of_observation,MEASURE,Measure,UNIT_MEASURE,Unit_of_measure,EXPEND_SOURCE,Expenditure_source,SPENDING_TYPE,Spending_type,PROGRAMME_TYPE,Programme_type,PRICE_BASE,Price_base,TIME_PERIOD,Time_period,OBS_VALUE,Observation_value,OBS_STATUS,Observation_status,UNIT_MULT,Unit_multiplier,DECIMALS,Decimals,CURRENCY,Currency,BASE_PER,Base_period
0,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2011,NaN,10.856,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
1,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2013,NaN,10.759,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
2,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2015,NaN,11.222,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
3,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2017,NaN,11.803,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
4,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2019,NaN,12.447,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN

Last 5 rows:

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference_area,FREQ,Frequency_of_observation,MEASURE,Measure,UNIT_MEASURE,Unit_of_measure,EXPEND_SOURCE,Expenditure_source,SPENDING_TYPE,Spending_type,PROGRAMME_TYPE,Programme_type,PRICE_BASE,Price_base,TIME_PERIOD,Time_period,OBS_VALUE,Observation_value,OBS_STATUS,Observation_status,UNIT_MULT,Unit_multiplier,DECIMALS,Decimals,CURRENCY,Currency,BASE_PER,Base_period
212,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,AUT,Austria,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2013,NaN,25.427,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
213,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,AUT,Austria,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2015,NaN,25.464,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
214,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,AUT,Austria,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2017,NaN,25.405,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
215,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,AUT,Austria,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2019,NaN,25.620,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
216,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,AUT,Austria,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2021,NaN,29.359,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN

Categorical Variables:

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference_area,FREQ,Frequency_of_observation,MEASURE,Measure,UNIT_MEASURE,Unit_of_measure,EXPEND_SOURCE,Expenditure_source,SPENDING_TYPE,Spending_type,PROGRAMME_TYPE,Programme_type,PRICE_BASE,Price_base,OBS_STATUS,Observation_status,Unit_multiplier,Decimals,CURRENCY,Currency
count,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217
unique,1,1,1,1,38,38,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
top,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,A,Normal value,Units,One,_Z,Not applicable
freq,217,217,217,217,6,6,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217

Numerical Variables:

,TIME_PERIOD,Time_period,OBS_VALUE,Observation_value,UNIT_MULT,DECIMALS,BASE_PER,Base_period
count,217.000000,0.0,217.000000,0.0,217.0,217.0,0.0,0.0
mean,2016.115207,NaN,20.744710,NaN,0.0,1.0,NaN,NaN
std,3.436002,NaN,5.436577,NaN,0.0,0.0,NaN,NaN
min,2011.000000,NaN,7.008000,NaN,0.0,1.0,NaN,NaN
25%,2013.000000,NaN,16.908000,NaN,0.0,1.0,NaN,NaN
50%,2017.000000,NaN,21.799000,NaN,0.0,1.0,NaN,NaN
75%,2019.000000,NaN,24.888000,NaN,0.0,1.0,NaN,NaN
max,2021.000000,NaN,33.242000,NaN,0.0,1.0,NaN,NaN

Missing values count for each column:

STRUCTURE                     0
STRUCTURE_ID                  0
STRUCTURE_NAME                0
ACTION                        0
REF_AREA                      0
Reference_area                0
FREQ                          0
Frequency_of_observation      0
MEASURE                       0
Measure                       0
UNIT_MEASURE                  0
Unit_of_measure               0
EXPEND_SOURCE                 0
Expenditure_source            0
SPENDING_TYPE                 0
Spending_type                 0
PROGRAMME_TYPE                0
Programme_type                0
PRICE_BASE                    0
Price_base                    0
TIME_PERIOD                   0
Time_period                 217
OBS_VALUE                     0
Observation_value           217
OBS_STATUS                    0
Observation_status            0
UNIT_MULT                     0
Unit_multiplier               0
DECIMALS                      0
Decimals                      0
CURRENCY                      0
Currency                      0
BASE_PER                    217
Base_period                 217
dtype: int64

Missing values percentage:

STRUCTURE                     0.0
STRUCTURE_ID                  0.0
STRUCTURE_NAME                0.0
ACTION                        0.0
REF_AREA                      0.0
Reference_area                0.0
FREQ                          0.0
Frequency_of_observation      0.0
MEASURE                       0.0
Measure                       0.0
UNIT_MEASURE                  0.0
Unit_of_measure               0.0
EXPEND_SOURCE                 0.0
Expenditure_source            0.0
SPENDING_TYPE                 0.0
Spending_type                 0.0
PROGRAMME_TYPE                0.0
Programme_type                0.0
PRICE_BASE                    0.0
Price_base                    0.0
TIME_PERIOD                   0.0
Time_period                 100.0
OBS_VALUE                     0.0
Observation_value           100.0
OBS_STATUS                    0.0
Observation_status            0.0
UNIT_MULT                     0.0
Unit_multiplier               0.0
DECIMALS                      0.0
Decimals                      0.0
CURRENCY                      0.0
Currency                      0.0
BASE_PER                    100.0
Base_period                 100.0
dtype: float64

Total duplicate rows: 0

In [4]:
df_oecd.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference_area,FREQ,Frequency_of_observation,MEASURE,Measure,UNIT_MEASURE,Unit_of_measure,EXPEND_SOURCE,Expenditure_source,SPENDING_TYPE,Spending_type,PROGRAMME_TYPE,Programme_type,PRICE_BASE,Price_base,TIME_PERIOD,Time_period,OBS_VALUE,Observation_value,OBS_STATUS,Observation_status,UNIT_MULT,Unit_multiplier,DECIMALS,Decimals,CURRENCY,Currency,BASE_PER,Base_period
0,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2011,NaN,10.856,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
1,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2013,NaN,10.759,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
2,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2015,NaN,11.222,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
3,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2017,NaN,11.803,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN
4,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_NET_GDP(1.0),Net total social expenditure in % GDP,I,TUR,Türkiye,A,Annual,SOCX,Social expenditure,PT_B1GQ,Percentage of GDP,ES50,Net total,_T,Total,_T,Total,_Z,Not applicable,2019,NaN,12.447,NaN,A,Normal value,0,Units,1,One,_Z,Not applicable,NaN,NaN

#### Select a Subset of Columns

In [5]:
# Select only these columns (subset)
selected_cols = ['REF_AREA', 'Reference_area', 'TIME_PERIOD', 'OBS_VALUE']

df_oecd = df_oecd[selected_cols]

#### Rename Columns

In [6]:
df_oecd.rename(columns={
    'REF_AREA': 'country_code',
    'Reference_area': 'country',
    'TIME_PERIOD': 'year_oecd',
    'OBS_VALUE': 'percent_gdp_social_spending'
}, inplace=True)

#### Get the latest year 2022 or most recent before

In [7]:
# Filter only rows with year ≤ 2022
df_oecd = df_oecd[df_oecd['year_oecd'] <= 2022]

# For each country, get its latest year
latest_year_per_country = df_oecd.groupby('country')['year_oecd'].max().reset_index()

# Merge back to get full rows matching latest year for each country
df_oecd = df_oecd.merge(latest_year_per_country, on=['country', 'year_oecd'], how='inner')

# Drop Year
df_oecd.drop(columns=["year_oecd"], inplace=True)

#### Check Unique Value country

In [8]:
df_oecd['country'].unique()

array(['Türkiye', 'Switzerland', 'Portugal', 'Netherlands', 'Israel',
       'Ireland', 'Colombia', 'United States', 'OECD', 'Spain', 'Chile',
       'Italy', 'Finland', 'Luxembourg', 'Czechia', 'Greece', 'Korea',
       'Slovenia', 'Slovak Republic', 'New Zealand', 'Australia',
       'France', 'Japan', 'Denmark', 'United Kingdom', 'Lithuania',
       'Sweden', 'Estonia', 'Latvia', 'Costa Rica', 'Mexico', 'Norway',
       'Poland', 'Belgium', 'Hungary', 'Germany', 'Iceland', 'Austria'],
      dtype=object)

In [9]:
df_oecd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country_code                 38 non-null     object
 1   country                      38 non-null     object
 2   percent_gdp_social_spending  38 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.0+ KB

In [10]:
df_oecd.head()

  country_code      country  percent_gdp_social_spending
0          TUR      Türkiye                       11.054
1          CHE  Switzerland                       26.058
2          PRT     Portugal                       24.676
3          NLD  Netherlands                       27.017
4          ISR       Israel                       18.590

In [11]:
df_oecd[df_oecd['country'] == 'OECD'].head()

  country_code country  percent_gdp_social_spending
8         OECD    OECD                        22.59

In [12]:
df_oecd = df_oecd[df_oecd['country'] != 'OECD']

In [13]:
df_oecd['country'] = df_oecd['country'].replace('Türkiye', 'Turkey')

In [14]:
df = pd.read_csv('happiness_gini_gdp.csv')

In [15]:
df_merged = pd.merge(
    df,
    df_oecd,
    on='country_code',  # Common column for joining
    how='left'         # Inner Join: keep only matching rows
)

In [16]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country_x                    134 non-null    object
 1   country_code                 134 non-null    object
 2   gini                         134 non-null    float64
 3   gdp_per_capita               134 non-null    float64
 4   happiness_score              134 non-null    float64
 5   country_y                    36 non-null     object
 6   percent_gdp_social_spending  36 non-null     float64
dtypes: float64(4), object(3)
memory usage: 7.5+ KB

In [17]:
df_merged[df_merged['country_y'].notna()].head()

,country_x,country_code,gini,gdp_per_capita,happiness_score,country_y,percent_gdp_social_spending
4,Australia,AUS,0.343326,64997.013654,7.1621,Australia,22.902
5,Austria,AUT,0.307016,52176.664914,7.1630,Austria,29.359
9,Belgium,BEL,0.265776,50807.204708,6.8050,Belgium,26.656
20,Chile,CHL,0.430427,15451.131958,6.1718,Chile,20.927
22,Colombia,COL,0.548193,6674.596019,5.7806,Colombia,17.379

In [18]:
df_merged.rename(columns={
    'country_x': 'country'
}, inplace=True)
df_merged.drop(columns=["country_y"], inplace=True)

In [19]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country                      134 non-null    object
 1   country_code                 134 non-null    object
 2   gini                         134 non-null    float64
 3   gdp_per_capita               134 non-null    float64
 4   happiness_score              134 non-null    float64
 5   percent_gdp_social_spending  36 non-null     float64
dtypes: float64(4), object(2)
memory usage: 6.4+ KB

In [20]:
df_merged.to_csv('processed_fourth.csv', index=False)